# actividad clase battleship 


In [1]:
import numpy as np

In [3]:
Cor=7,7
BA=13



BN=np.zeros((Cor))
BN
def board ():
    while BN.sum() < BA:
        BT = input ("Defina cordenada de la nave")
        c1, c2 = BT.split(',')
        c1=int (c1)
        c2= int (c2)
        BN [c1,c2] =1
        print(BN)
        print("----------")  
    return BN    
   
print("----------")        
print(board())
       

----------
Defina cordenada de la nave0,0
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
----------
Defina cordenada de la nave0,2
[[1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
----------
Defina cordenada de la nave0,1
[[1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
----------
Defina cordenada de la nave0,4
[[1. 1. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
----------
Defina cordenada de la nave1,2
[[1. 1. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0

In [ ]:
BN2=np.zeros((Cor))
BN2
def board1 ():
    
    
    while BN2.sum() < BA:
        BT = input ("Defina cordenada de la nave")
        c1, c2 = BT.split(',')
        c1=int (c1)
        c2= int (c2)
        BN2 [c1,c2] =1
        print(BN2)
    return BN2    
   
        
print("----------")        
print(board1())

----------
Defina cordenada de la nave0,0
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [8]:
print (BN)
print (BN2)

[[1. 1. 1. 0. 1. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
[[0. 1. 1. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1.]]


In [2]:
Cor=7,7
BA=13

A =np.zeros((Cor))
A


A[0,:4]=1
A[2,:3]=1
A[6,:3]=1
A[4,5]=1
A[4,6]=1
A

array([[1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.]])

In [3]:
Cor=7,7
BA=13

B1 =np.zeros((Cor))
B1


B1[0,:4]=1
B1[2,:3]=1
B1[6,:3]=1
B1[4,5]=1
B1[4,6]=1
B1

array([[1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.]])

In [ ]:
Jugador1 = A
Jugador2= B1
B=np.zeros((Cor))
B
B3=np.zeros((Cor))
B3

BnJugador1 =np.zeros((Cor))
BnJugador1 

def juego (): 
    while Jugador1.sum() > 0:
        Cor = input ("Turno jugador 1 Cordenada a atacar")
        A1, A2 = Cor.split(',')
        A1= int (A1)
        A2 = int (A2)
        if (Jugador1)[A1,A2] ==1:
            (Jugador1)[A1,A2] =5 # Si pongo un str me sale un error
            print("------le has dado al barco-----")
            print(A)
        else:
            B [A1,A2] =1
            print ("------lo siento has fallado-----")
            print(B)
            Cor2 = input ("turno jugador dos cordenadas")
        while Jugador2.sum()>0:
            D1,D2 = Cor2.split(',')
            D1 = int(D1)
            D2 = int(D2)
            if Jugador2 [D1,D2]==1:
                Jugador2 [D1,D2]=5
                print ("le had dado al baroC")
                print(B1)
            else:
                B3[D1,D2] =1
                print("----- lo siento has fallado")
                print(B3)
            return juego ()
            
            
               
        
        
   
juego ()

Turno jugador 1 Cordenada a atacar0,6
------lo siento has fallado-----
[[0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
turno jugador dos cordenadas0,6
----- lo siento has fallado
[[0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
Turno jugador 1 Cordenada a atacar0,5
------lo siento has fallado-----
[[0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
turno jugador dos cordenadas0,0
le had dado al baroC
[[5. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0.]]
